name: Check

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
          DATA: |
            A=1
            B=2
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.x'
          - run: python main.py
    job-a:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                a: [1, 2]
        steps:
            - run: echo ${{ matrix.a }}

          
