name: Check

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: exit 0
            - name: Step 2
              run: exit 1
            - name: Step 3
              if: ${{ always() }}
              run: exit 0